import { APP_CONFIG } from "@/config/app.config";

export const SERVICE_UUID = APP_CONFIG.SERVICE_UUID;
export const AUDIO_CHAR_UUID = APP_CONFIG.AUDIO_CHAR_UUID;
export const TEXT_CHAR_UUID = APP_CONFIG.TEXT_CHAR_UUID;

export const DEVICE_NAME = APP_CONFIG.DEVICE_NAME_PREFIX;

export const PROTOCOL = {
  START_VOICE: "START_V",
  START_SILENT: "START_S",
  END: "END",
  GET_TIME: "GET_TIME",
  REQ_TIME: "REQ_TIME",
  TIME_PREFIX: "TIME:",
} as const;

export const BLE_CONFIG = {
  SCAN_TIMEOUT: 10000,
  RECONNECT_DELAY: 2000,
  MAX_RECONNECT_ATTEMPTS: 5,
} as const;
